---
- name: Setup workload
  hosts: k8n_control_plane
  tasks:
    - name: Install last version of web-application
      kubernetes.core.helm:
        name: web-application
        chart_ref: netology-yc-helm/web-application
        #chart_version: Omitted to install the latest version!
        update_repo_cache: true
        release_namespace: default
        create_namespace: false
