---
- name: Scheduled tasks
  hosts: k8n_control_plane
  tasks:
    - name: Periodic web-application update
      ansible.builtin.cron:
        name: "helm-update-30min"
        state: present
        minute: "*/30"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: '/usr/local/bin/helm repo add diploma-chart https://e-zh.github.io/netology-yc-helm/charts/;
        /usr/local/bin/helm repo update;
        /usr/local/bin/helm upgrade --install web-application diploma-chart/web-application --atomic;'
